### ISSUE TITLE
Service Graph Template: "directConnect" should be made customizable

### ISSUE THREAD

**Issue by alexpantea** [netascode/terraform-aci-service-graph-template#12]
Service Graph Template: "directConnect" should be made customizable. It is hardcoded to:

directConnect = "no"

both on consumer and provider.

These 2 resources need to be changed: 
    - "aci_rest_managed" "vnsAbsConnection_Consumer"
    - "aci_rest_managed" "vnsAbsConnection_Provider"

https://github.com/netascode/terraform-aci-service-graph-template/blob/d7a426a1f48c42495267cae427f02bca3a50ffbb/main.tf#L106-L117

**Comment by danischm** [comment]
Added with the referenced PR.
